using System;
using System.IO;
using System.IO.Compression;
using NUnit.Framework;
using Assert = NUnit.Framework.Legacy.ClassicAssert;

namespace Splatter.Pmc.Tests
{
    /// <summary>
    /// PmcQr encoder: golden matrices (generated by the `qrcode` npm package with the same
    /// version/level/mode/mask), structure, capacity limits, mask selection, PNG rendering.
    /// Port of the Godot tests/suites/test_qr.gd. The broad corpus check with independent
    /// decoders lives in tests/node/qr-decode.mjs.
    /// </summary>
    [TestFixture]
    public class QrTests
    {
        private sealed class Golden
        {
            public string Text;
            public int Ecc;
            public int Version;
            public int Mask;
            public string Mode;
            public string[] Rows;
        }

        private static readonly Golden[] Goldens =
        {
            new Golden
            {
                Text = "HELLO WORLD", Ecc = 2, Version = 1, Mask = 0, Mode = "alphanumeric",
                Rows = new[]
                {
                    "111111101100001111111",
                    "100000101001001000001",
                    "101110101001101011101",
                    "101110101000001011101",
                    "101110101010001011101",
                    "100000100010001000001",
                    "111111101010101111111",
                    "000000001000000000000",
                    "011010110000101011111",
                    "010000001111000010001",
                    "001101110110001011000",
                    "011011010011010101110",
                    "100010101011101110101",
                    "000000001101001000101",
                    "111111101010000101100",
                    "100000100101101101000",
                    "101110101010001111111",
                    "101110100101010100010",
                    "101110101001011101001",
                    "100000101011110001011",
                    "111111100001011100001",
                },
            },
            new Golden
            {
                Text = "http://192.168.1.87:8086/?code=ABCD", Ecc = 1, Version = 3, Mask = 7, Mode = "byte",
                Rows = new[]
                {
                    "11111110000010100101101111111",
                    "10000010011000001100001000001",
                    "10111010011000110110001011101",
                    "10111010001001000001101011101",
                    "10111010010000000000101011101",
                    "10000010101110010111101000001",
                    "11111110101010101010101111111",
                    "00000000010011010100000000000",
                    "10010110101100101011110100000",
                    "11010001001101011000001101001",
                    "00111110100101101101110111110",
                    "10100001110111000010111001110",
                    "10101010111010101111001101011",
                    "01110001000101110011000100100",
                    "11010110101101101000100100111",
                    "11000000100100000110110011010",
                    "01000010001011000101000001010",
                    "00010001000101111000111000001",
                    "10100010110010100110110001011",
                    "00101000100010111110010100011",
                    "10011110001010001001111110100",
                    "00000000111100111000100010111",
                    "11111110011110001100101010010",
                    "10000010100100111011100011101",
                    "10111010011010010100111111001",
                    "10111010111111001100111010010",
                    "10111010010000100101110111001",
                    "10000010010011111101110001010",
                    "11111110110010000101110000010",
                },
            },
            new Golden
            {
                Text = "https://random-words-here.trycloudflare.com/?code=WXYZ", Ecc = 3, Version = 6, Mask = 2, Mode = "byte",
                Rows = new[]
                {
                    "11111110110000111111000000000111101111111",
                    "10000010110001110100111010011010001000001",
                    "10111010110001101110001010111001001011101",
                    "10111010011101011001111010001000101011101",
                    "10111010000010101110010101101001101011101",
                    "10000010111000101011000101110110101000001",
                    "11111110101010101010101010101010101111111",
                    "00000000100100110010011000100010100000000",
                    "00111010100001011111101000010100111100111",
                    "11100000101001101110011000101011111110111",
                    "11000010000111011101101000111110100010000",
                    "10001101010110111010100110101011100111001",
                    "01111011011100011010010110100101110101101",
                    "01011100010010110101001101111010101111011",
                    "00100011000111000111100111100000010011100",
                    "11000000110101111000011011101000001111001",
                    "01001110111110011111110110000111110100110",
                    "01100001110000111010111111001111101111101",
                    "00100111000001100100010001011110110010000",
                    "01100100110011000100001001101010001011000",
                    "10010011100001111111011110001010010000101",
                    "01100001010100100010111100101011111110011",
                    "01011111101111101001010101110010000011100",
                    "00110000011111111101000000111000011111011",
                    "01000011000100101111000001010101000000100",
                    "11100101101001001100011110101011011111001",
                    "01011110100111000111001110110000101110010",
                    "10010100101010001110111100111001100111001",
                    "00111110000010101011101100011111100001101",
                    "10001000100001100011001100010110100111111",
                    "10100110111101010110110001011100111001100",
                    "10110101011110010010110101010011111011000",
                    "10111110101010011110101101010100111111111",
                    "00000000110001000111010011001110100011111",
                    "11111110010010010111010011111101101011110",
                    "10000010000010011101011110000111100011000",
                    "10111010100001100010001010111000111111101",
                    "10111010100010111001111101101110010101101",
                    "10111010111011100001001001010101111111110",
                    "10000010001101001111010011101010101011010",
                    "11111110000011010111110100100101000110100",
                },
            },
            new Golden
            {
                Text = "Grüße ✓ 0123456789 https://example.com/x", Ecc = 0, Version = 7, Mask = 5, Mode = "byte",
                Rows = new[]
                {
                    "111111100101101111100001101001110100101111111",
                    "100000100111011100101011001000001101001000001",
                    "101110100100101101111010000101010101001011101",
                    "101110101110010110101011011100001001101011101",
                    "101110101010100101111111100111010111101011101",
                    "100000100111111100111000110110100100001000001",
                    "111111101010101010101010101010101010101111111",
                    "000000000010001001101000111011011100100000000",
                    "110001110111011100111111111001000111000011000",
                    "011001010001101101110011111000110010101101010",
                    "110101100100000111010000101010000011101100001",
                    "010101001101110110000001111100100111111101011",
                    "010011111011111110001011110110100101110111111",
                    "111000011000010110100001111100101111011101010",
                    "010111111111000111010000100101111100000100100",
                    "011101001001011100001011110001010111001111011",
                    "110101101100100001010000110101010011000110100",
                    "110000011101010000100110100101100000100000100",
                    "000010111011000011111100010011011001100000100",
                    "111110001100101001111110000001010001100000101",
                    "111011111111011000101111110010000001111111100",
                    "101010001100101011111000101001011010100010101",
                    "001110101110111000111010110010100000101011011",
                    "101110001110001001111000111011111010100010001",
                    "100011111100100111111111100010101110111110100",
                    "111101000100100111101001010001100000110111011",
                    "010011110111100111010010111011010010000110010",
                    "101100011100111100010001010110101101111101010",
                    "011111101001100101011010001101111110000000110",
                    "001100000100110110100001011100101111100011010",
                    "110000101110111100010110111110100111111100011",
                    "011001001000110110000100101010011010011001110",
                    "010001101110100001001101100000110001111000000",
                    "101011010101011010101110101011101011000010101",
                    "000010101000011000101101100100010111011001110",
                    "011110010111001001100100100001010001100000100",
                    "100110110011100011111111101001011011111110100",
                    "000000001111000001101000100011010000100011100",
                    "111111101110011000101010110010100001101011111",
                    "100000101001000011111000110100110010100010100",
                    "101110100011111100111111101001110100111110011",
                    "101110100110100111101001111101100101100011001",
                    "101110100000111100000011111001010101101001011",
                    "100000101000110110000110111100100111100001000",
                    "111111101111100101011111001101111110111100110",
                },
            },
        };

        [Test]
        public void GoldenMatricesMatchQrcodeNpm()
        {
            foreach (var g in Goldens)
            {
                var m = PmcQr.EncodeAdvanced(g.Text, (PmcQr.Ecc)g.Ecc, g.Version, g.Version, g.Mask, g.Mode);
                Assert.IsNotNull(m, $"encodes {g.Text}");
                Assert.AreEqual(g.Rows.Length, m.Size, $"size for {g.Text}");
                var rows = m.ToRows();
                int diff = 0;
                for (int y = 0; y < rows.Length; y++)
                    for (int x = 0; x < rows[y].Length; x++)
                        if (rows[y][x] != g.Rows[y][x])
                            diff++;
                Assert.AreEqual(0, diff, $"module differences for {g.Text} (v{g.Version} mask {g.Mask})");
            }
        }

        [Test]
        public void AutoVersionAndMode()
        {
            var url = PmcQr.EncodeAdvanced("http://192.168.1.87:8086/?code=ABCD");
            Assert.AreEqual(3, url.Version, "LAN URL at M fits version 3");
            Assert.AreEqual("byte", url.Mode);
            Assert.AreEqual((int)PmcQr.Ecc.M, url.Ecc, "default level is M");
            Assert.AreEqual(29, url.Size);
            Assert.AreEqual("alphanumeric", PmcQr.EncodeAdvanced("HELLO WORLD", PmcQr.Ecc.Q).Mode);
            Assert.AreEqual("numeric", PmcQr.EncodeAdvanced("0123456789").Mode);
            Assert.AreEqual(1, PmcQr.EncodeAdvanced("").Version, "empty text encodes");
            Assert.AreEqual(4, PmcQr.EncodeAdvanced("https://random-words-here.trycloudflare.com/?code=WXYZ", PmcQr.Ecc.L).Version);
            Assert.AreEqual(6, PmcQr.EncodeAdvanced("https://random-words-here.trycloudflare.com/?code=WXYZ", PmcQr.Ecc.H).Version);
        }

        [Test]
        public void EncodeReturnsModuleGrid()
        {
            var simple = PmcQr.Encode("HELLO WORLD");
            var m = PmcQr.EncodeAdvanced("HELLO WORLD");
            Assert.IsNotNull(simple);
            Assert.AreEqual(m.Size, simple.Size);
            for (int y = 0; y < m.Size; y++)
                for (int x = 0; x < m.Size; x++)
                    Assert.AreEqual(m.GetModule(x, y), simple[x, y], $"module {x},{y}");
            Assert.IsNull(PmcQr.Encode(new string('a', 3000)), "oversize text returns null");
        }

        [Test]
        public void CapacityLimits()
        {
            // Version 1-L holds 17 bytes, version 40-L 2953 bytes, version 40-H 1273 bytes.
            Assert.AreEqual(1, PmcQr.EncodeAdvanced(new string('a', 17), PmcQr.Ecc.L).Version);
            Assert.AreEqual(2, PmcQr.EncodeAdvanced(new string('a', 18), PmcQr.Ecc.L).Version);
            Assert.AreEqual(40, PmcQr.EncodeAdvanced(new string('a', 2953), PmcQr.Ecc.L).Version);
            Assert.IsNull(PmcQr.EncodeAdvanced(new string('a', 2954), PmcQr.Ecc.L), "2954 bytes at L does not fit");
            Assert.IsNull(PmcQr.EncodeAdvanced(new string('a', 1274), PmcQr.Ecc.H), "1274 bytes at H does not fit");
            Assert.AreEqual(40, PmcQr.EncodeAdvanced(new string('7', 7089), PmcQr.Ecc.L).Version, "7089 digits fit version 40-L");
            Assert.IsNull(PmcQr.EncodeAdvanced("abc", PmcQr.Ecc.M, 1, 1, -1, "numeric"), "invalid numeric text rejected");
            Assert.IsNull(PmcQr.EncodeAdvanced("abc", PmcQr.Ecc.M, 1, 1, -1, "kanji"), "unknown mode rejected");
        }

        [Test]
        public void CapacityBoundariesPerLevelAndVersion()
        {
            // Exactly-at-capacity encodes succeed for every level at a few versions.
            foreach (int v in new[] { 1, 7, 20, 40 })
            {
                for (int ecc = 0; ecc < 4; ecc++)
                {
                    int capBits = PmcQr.NumDataCodewords(v, ecc) * 8;
                    int ccBits = PmcQr.CharCountBits("byte", v);
                    int maxBytes = Math.Min((capBits - 4 - ccBits) / 8, (1 << ccBits) - 1);
                    var m = PmcQr.EncodeAdvanced(new string('a', maxBytes), (PmcQr.Ecc)ecc, v, v);
                    Assert.IsNotNull(m, $"v{v} ecc {ecc} at capacity {maxBytes}");
                    Assert.AreEqual(v, m.Version);
                }
            }
        }

        [Test]
        public void Structure()
        {
            var big = PmcQr.EncodeAdvanced(new string('x', 500), PmcQr.Ecc.M);
            Assert.AreEqual(17, big.Version, "500 bytes at M need version 17");
            var url = PmcQr.EncodeAdvanced("http://192.168.1.87:8086/?code=ABCD");
            foreach (var m in new[] { url, big })
            {
                // Finder pattern corners and timing pattern.
                Assert.IsTrue(m.GetModule(0, 0) && m.GetModule(6, 6) && !m.GetModule(7, 7), "top-left finder");
                Assert.IsTrue(m.GetModule(m.Size - 1, 0) && m.GetModule(0, m.Size - 1), "other finders");
                Assert.IsTrue(m.GetModule(8, m.Size - 8), "dark module");
                bool timingOk = true;
                for (int i = 8; i < m.Size - 8; i++)
                    if (m.GetModule(i, 6) != (i % 2 == 0) || m.GetModule(6, i) != (i % 2 == 0))
                        timingOk = false;
                Assert.IsTrue(timingOk, $"timing patterns v{m.Version}");
                Assert.IsTrue(!m.GetModule(-1, 0) && !m.GetModule(m.Size, 0), "out of range is light");
            }
            int dark = 0;
            foreach (byte b in big.Modules)
                if (b == 1)
                    dark++;
            Assert.IsTrue(dark > big.Size * big.Size * 0.4 && dark < big.Size * big.Size * 0.6, "dark balance");
        }

        [Test]
        public void MaskSelection()
        {
            const string url = "http://192.168.1.87:8086/?code=ABCD";
            var auto = PmcQr.EncodeAdvanced(url, PmcQr.Ecc.M);
            var penalties = new int[8];
            for (int msk = 0; msk < 8; msk++)
            {
                var forced = PmcQr.EncodeAdvanced(url, PmcQr.Ecc.M, 1, 40, msk);
                Assert.AreEqual(msk, forced.Mask);
                int w = forced.Size + 1;
                int n = forced.Size * w + 1;
                var r = new byte[(n + 7) & ~7];
                for (int i = 0; i < r.Length; i++)
                    r[i] = 2;
                var c = (byte[])r.Clone();
                for (int y = 0; y < forced.Size; y++)
                {
                    for (int x = 0; x < forced.Size; x++)
                    {
                        byte v = forced.GetModule(x, y) ? (byte)1 : (byte)0;
                        r[y * w + 1 + x] = v;
                        c[x * w + 1 + y] = v;
                    }
                }
                penalties[msk] = PmcQr.Penalty(r, c, forced.Size);
            }
            int min = penalties[0];
            foreach (int p in penalties)
                min = Math.Min(min, p);
            Assert.AreEqual(min, penalties[auto.Mask], $"auto mask has the lowest penalty ({string.Join(",", penalties)})");
        }

        [Test]
        public void ForcedMaskOutOfRangeFallsBackToAuto()
        {
            var m = PmcQr.EncodeAdvanced("HELLO WORLD", PmcQr.Ecc.M, 1, 40, 99);
            Assert.IsTrue(m.Mask >= 0 && m.Mask <= 7);
        }

        [Test]
        public void Utf8ByteMode()
        {
            var m = PmcQr.EncodeAdvanced("Grüße aus Köln — ünïcödé ✓");
            Assert.AreEqual("byte", m.Mode);
            // Multi-byte chars count toward byte capacity, not char capacity.
            var ascii = PmcQr.EncodeAdvanced(new string('a', 20), PmcQr.Ecc.M);
            var utf8 = PmcQr.EncodeAdvanced(new string('é', 20), PmcQr.Ecc.M);
            Assert.IsTrue(utf8.Version > ascii.Version, "40 UTF-8 bytes need a bigger version than 20 ASCII bytes");
            Assert.IsNull(PmcQr.EncodeAdvanced(new string('é', 2000), PmcQr.Ecc.H), "4000 UTF-8 bytes exceed 40-H");
        }

        [Test]
        public void EncodePngRenders()
        {
            var url = PmcQr.EncodeAdvanced("http://192.168.1.87:8086/?code=ABCD");
            byte[] png = PmcQr.EncodePng(url, 8, 4);
            var img = DecodePng(png);
            Assert.AreEqual((29 + 8) * 8, img.Width);
            Assert.AreEqual((29 + 8) * 8, img.Height);
            Assert.IsTrue(img.IsLight(0, 0), "quiet zone is white");
            Assert.IsFalse(img.IsLight(4 * 8 + 3, 4 * 8 + 3), "first module is black");
            int mismatch = 0;
            for (int y = 0; y < url.Size; y++)
                for (int x = 0; x < url.Size; x++)
                    if (img.IsLight((x + 4) * 8 + 4, (y + 4) * 8 + 4) == url.GetModule(x, y))
                        mismatch++;
            Assert.AreEqual(0, mismatch, "every module rendered");
            Assert.AreEqual(29, DecodePng(PmcQr.EncodePng(url, 1, 0)).Width, "1 px, no quiet zone");
            Assert.IsNotNull(PmcQr.EncodePng("http://192.168.1.87:8086/?code=ABCD", PmcQr.Ecc.M, 8, 4), "text overload");
            Assert.IsNull(PmcQr.EncodePng(new string('a', 3000), PmcQr.Ecc.L, 8, 4), "unencodable text returns null");
        }

        // Minimal decoder for the PNGs PmcQr.EncodePng writes (8-bit RGB, filter 0 rows).
        private sealed class PngImage
        {
            public int Width;
            public int Height;
            public byte[] Pixels; // RGB

            public bool IsLight(int x, int y)
            {
                int o = (y * Width + x) * 3;
                return Pixels[o] > 127;
            }
        }

        private static PngImage DecodePng(byte[] png)
        {
            Assert.IsNotNull(png);
            Assert.AreEqual(new byte[] { 0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A },
                new ArraySegment<byte>(png, 0, 8).ToArray(), "PNG signature");
            int pos = 8;
            int width = 0, height = 0;
            var idat = new MemoryStream();
            while (pos < png.Length)
            {
                int len = ReadU32BE(png, pos);
                string type = System.Text.Encoding.ASCII.GetString(png, pos + 4, 4);
                if (type == "IHDR")
                {
                    width = ReadU32BE(png, pos + 8);
                    height = ReadU32BE(png, pos + 12);
                    Assert.AreEqual(8, png[pos + 16], "bit depth");
                    Assert.AreEqual(2, png[pos + 17], "color type RGB");
                    Assert.AreEqual(0, png[pos + 20], "no interlace");
                }
                else if (type == "IDAT")
                {
                    idat.Write(png, pos + 8, len);
                }
                pos += 12 + len;
            }
            Assert.IsTrue(width > 0 && height > 0, "IHDR parsed");
            var zlib = idat.ToArray();
            byte[] raw;
            using (var ds = new ZLibStream(new MemoryStream(zlib), CompressionMode.Decompress))
            using (var outMs = new MemoryStream())
            {
                ds.CopyTo(outMs);
                raw = outMs.ToArray();
            }
            int stride = width * 3 + 1;
            Assert.AreEqual(height * stride, raw.Length, "inflated size");
            var pixels = new byte[width * height * 3];
            for (int y = 0; y < height; y++)
            {
                Assert.AreEqual(0, raw[y * stride], "filter 0");
                Array.Copy(raw, y * stride + 1, pixels, y * width * 3, width * 3);
            }
            return new PngImage { Width = width, Height = height, Pixels = pixels };
        }

        private static int ReadU32BE(byte[] buf, int offset)
        {
            return (buf[offset] << 24) | (buf[offset + 1] << 16) | (buf[offset + 2] << 8) | buf[offset + 3];
        }
    }
}
